# If you change this resolver, you may need to update the GHC version in `shell.nix` accordingly!
resolver: nightly-2022-09-16

# Currently required by cas-hashable-s3 because `aws` dependency has invalid `base16-bytestring` and `base64-bytestring` boundaries.
allow-newer: true

packages:
  - cas/hashable
  - cas/s3
  - cas/store
  - docker-client
  - funflow
  - funflow-examples

# Reminder: These are extra packages which don't exist in the
# stack snapshot we are using.
extra-deps:
  - aws-0.22
  - github: tweag/kernmantle
    commit: 19e018449f4fba68d383611a9d38a1b9e04e81ee
    subdirs:
      - kernmantle
      - batteries
      - caching
  # We use iHaskell for the tutorials
  - github: gibiansky/IHaskell
    commit: 0ff0145c03f6665cfed426f900c9a7561c821c4f
    subdirs:
      - .
      - ipython-kernel
      - ghc-parser
      - ihaskell-display/ihaskell-aeson
      - ihaskell-display/ihaskell-blaze
      - ihaskell-display/ihaskell-charts
      - ihaskell-display/ihaskell-diagrams
      - ihaskell-display/ihaskell-gnuplot
      - ihaskell-display/ihaskell-hatex
      - ihaskell-display/ihaskell-juicypixels
      - ihaskell-display/ihaskell-magic
      - ihaskell-display/ihaskell-widgets
  # We also provide hvega for plotting
  - github: DougBurke/hvega
    commit: 8348642a9bd9e05b2966f29ef114e673fe26a37c
    subdirs:
      - ihaskell-hvega
