name: cas-hashable
version: 1.0.1
synopsis: A hashing class for content-addressed storage
description: A hashing class for content-addressed storage. Content can be hashed either by value or through an IO action. Part of the funflow ecosystem.
license: MIT
license-file: LICENSE
maintainer: Matthias Meschede <matthias.meschede@tweag.io>
github: tweag/funflow
category: Control
author: Tom Nielsen, Nicholas Clarke, Andreas Herrmann

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - aeson
  - bytestring
  - clock
  - containers
  - cryptonite
  - ghc-prim
  - hashable
  - integer-gmp
  - memory
  - path
  - path-io
  - safe-exceptions
  - scientific
  - text
  - time
  - unix
  - unordered-containers
  - vector

extra-source-files: changelog.md

library:
  source-dirs: src
