name: cas-hashable
version: 2.0.0
synopsis: A hashing class for content-addressed storage
description: A hashing class for content-addressed storage. Content can be hashed either by value or through an IO action. Part of the funflow ecosystem.
license: MIT
license-file: LICENSE
maintainer: Matthias Meschede <matthias.meschede@tweag.io>
github: tweag/funflow
category: Control
author: Tom Nielsen, Nicholas Clarke, Andreas Herrmann

ghc-options: -Wall

dependencies:
  - base                          >= 4.9 && < 5
  - aeson                         >= 2.1.0 && < 2.2
  - bytestring
  - clock
  - containers
  - cryptonite
  - ghc-prim
  - hashable                      >= 1.4.1 && < 1.5
  - integer-gmp
  - memory
  - path
  - path-io
  - safe-exceptions
  - scientific
  - text                          >= 2.0.1 && < 2.1
  - time
  - unix
  - unordered-containers
  - vector

extra-source-files: changelog.md

library:
  source-dirs: src

tests:
  perf:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -rtsopts -O2
    dependencies:
      - base >=4.6 && <5
      - cas-hashable
