name: cas-hashable-s3
version: 1.0.0
synopsis: ContentHashable instances for S3 objects
description: Provides ContentHashable instances for S3 objects
license: MIT
license-file: LICENSE
maintainer: Matthias Meschede <matthias.meschede@tweag.io>
github: tweag/funflow
category: Control
author: Tom Nielsen, Nicholas Clarke, Andreas Herrmann

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - aeson >= 2.0
  - aws
  - cas-hashable
  - constraints
  - http-conduit
  - reflection
  - resourcet

library:
  source-dirs: src
