name: funflow
version: 2.0.0
synopsis: Make composable workflows
description: See README at <https://github.com/tweag/funflow2>
maintainer: Matthias Meschede <matthias.meschede@tweag.io>
github: tweag/funflow2
category: Development

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - bytestring
  - cas-store
  - cas-hashable
  - containers
  - data-default
  - directory
  - docker-client
  - external-executor
  - hashable
  - http-client
  - kernmantle
  - kernmantle-batteries
  - kernmantle-caching
  - modern-uri
  - mtl
  - path
  - path-io
  - safe-exceptions
  - store
  - temporary
  - text
  - unix-compat
  - unliftio
  - unordered-containers
  - utf8-string
  - yaml

library:
  source-dirs: src

tests:
  test-funflow:
    main: TestFunflow.hs
    source-dirs: test/flows
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - base >=4.6 && <5
      - funflow
      - directory
  unit-tests:
    main: Unit.hs
    source-dirs: test/unit
    ghc-options:
      - -Wall
      - -threaded
    dependencies:
      - base >=4.6 && <5
      - cryptonite
      - funflow
      - QuickCheck
      - tasty
      - tasty-hunit
