name: funflow-tutorial
version: 2.0.0
synopsis: A tutorial on how to use funflow2
description: See README at <https://github.com/tweag/funflow2>
maintainer: Matthias Meschede <matthias.meschede@tweag.io>
github: tweag/funflow2
category: Development

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - funflow
  - inliterate
library:
  source-dirs: lib

executables:
  quick-reference:
    main: src/QuickReference.hs
    source-dirs: .
    dependencies:
      - base >=4.6 && <5
      - funflow-tutorial
    build-tools:
      - inliterate:inlitpp
  tutorial1:
    main: src/Tutorial1.hs
    source-dirs: .
    dependencies:
      - base >=4.6 && <5
      - funflow-tutorial
    build-tools:
      - inliterate:inlitpp
  tutorial2:
    main: src/Tutorial2.hs
    source-dirs: .
    dependencies:
      - base >=4.6 && <5
      - funflow-tutorial
    build-tools:
      - inliterate:inlitpp
  wordcount:
    main: src/WordCount.hs
    source-dirs: .
    dependencies:
      - base >=4.6 && <5
      - funflow-tutorial
      - regex-posix 
      - text
      - containers
    build-tools:
      - inliterate:inlitpp
  