# A simple example of how to include funflow and its dependencies
# in your own `stack` project.

resolver: lts-16.22

packages:
- .

# Not all of funflow's dependencies can be found in stackage snapshots
# So you'll need to add them here.
#
# Note that the versions/commits below may be different than
# at the writing of this
extra-deps:
- aws-0.22
- direct-sqlite-2.3.26
- sqlite-simple-0.4.18.0
- store-0.7.4
- store-core-0.4.4.2
- th-utilities-0.2.4.0
- vinyl-0.12.2
- github: tweag/kernmantle
  commit: 79e5cf5ecfe73f41206aa78930256a2f171bc9b8
  subdirs:
  - kernmantle
  - batteries
  - caching
# Funflow libraries
- git: https://github.com/tweag/funflow.git
  commit: 32536980ce1ede26642cb34f2ea6a9175ad50001
  subdirs:
  - funflow
  - docker-client
  - cas/hashable
  - cas/s3
  - cas/store
