name: funflow-examples
version: 0.1.0
synopsis: Example applications of the funflow library
description: See README at <https://github.com/tweag/funflow/funflow-examples>
license: MIT
license-file: LICENSE
maintainer: Vince Reuter <vince.reuter@tweag.io>
github: tweag/funflow/funflow-examples
category: Development

ghc-options: -Wall

dependencies:
  - base >=4.10 && < 5
  - bytestring
  - cas-store
  - cas-hashable
  - containers
  - data-default
  - directory
  - funflow
  - kernmantle
  - parsec
  - path
  - path-io
  - safe-exceptions
  - text
  - unix

executables:
  makefile-tool:
    main: Main.hs
    source-dirs: makefile-tool/src

library:
  source-dirs: makefile-tool/src
