name: docker-client
version: 0.1.0
synopsis: Funflow's internal docker engine client
description: See README at <https://github.com/tweag/funflow2>
maintainer: Dorran Howell <dorran.howell@tweag.io>
github: tweag/funflow2
category: Development

ghc-options:
  - -Wall

dependencies:
  - base >=4.6 && <5
  - aeson
  - binary
  - bytestring
  - conduit
  - conduit-extra
  - directory
  - http-client
  - http-conduit
  - http-types
  - mtl
  - network
  - path
  - path-io
  - resourcet
  - string-conversions
  - tar-conduit
  - text
  - unix-compat


library:
  source-dirs: src

tests:
  primary:
    main: Test.hs
    source-dirs: test
    dependencies:
      - base >=4.6 && <5
      - directory
      - docker-client
      - http-types
      - mtl
      - tasty
      - tasty-hunit
      - temporary
      - text
      - unix-compat
